### ISSUE TITLE
Job Postings Search Specific to A Certain Location

### ISSUE THREAD

**Issue by hjhjhjh535** [ArshKA/LinkedIn-Job-Scraper#8]
### I appreciate the open-source contribution. However, I have a question: is it possible to specify the job postings for a particular location in the search?

**Comment by AndhikaWB** [comment]
Hi, sorry for the late reply

Have you tried running the script? It will follow your LinkedIn account settings (including location). The one provided in this repo is scrapped from the US since the owner is from there

If that's not what you want, you can inspect the network using browser developer tools to investigate the right search query for custom location (and modify the script URL after that). Unfortunately, I can't do that for you since I no longer use this project

**Comment by hjhjhjh535** [comment]
Alright, thank you very much for your answer!
After running the script, the location of the data I scraped indeed follows the LinkedIn account settings, meaning I can just set the location in my account accordingly.

**Comment by AndhikaWB** [comment]
I'm closing this since we already have the workaround in #9 
Thank you
